import "../styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
export const metadata = {
  title:
    "Top CCTV and IT Solutions in Faridabad | Server Maintenance, Networking and Firewall Solutions for your Business",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
